//Common
export const BAD_REQUEST_EXCEPTION = 'BAD_REQUEST_EXCEPTION';
export const NOT_FOUND_EXCEPTION = 'NOT_FOUND_EXCEPTION';

//auth
export const USER_NOT_LOGIN = 'USER_NOT_LOGIN';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const USER_IS_INACTIVE = 'USER_IS_INACTIVE';
export const USER_NOT_PERMISSION = 'USER_NOT_PERMISSION';
export const EMAIL_IS_EXIST = 'EMAIL_IS_EXIST';
export const USER_IS_EXIST = 'USER_IS_EXIST';
export const EMAIL_OR_PASSWORD_IS_INCORRECT = 'EMAIL_OR_PASSWORD_IS_INCORRECT';
export const CONFIRM_PASSWORD_NOT_MATCH = 'CONFIRM_PASSWORD_NOT_MATCH';
export const EMAIL_NOT_EXIST = 'EMAIL_NOT_EXIST';
export const PASSWORD_IS_INCORRECT = 'PASSWORD_IS_INCORRECT';
export const TOKEN_INVALID = 'TOKEN_INVALID';
